publish_to: 'https://pub.dev'
name: struct_generator
version: 0.1.0
homepage: https://github.com/sivakumarjogi/struct_generator
description: 'CLI generator for Flutter module/page/bloc skeletons'
environment:
  sdk: '>=3.0.0 <4.0.0'
executables:
  struct_generator: struct_generator

dependencies:
  path: ^1.9.1
  mustache_template: ^2.0.2
  args: ^2.7.0
  io: ^1.0.5

dev_dependencies:
  lints: ^6.0.0
  test: ^1.27.0
